### ISSUE TITLE
build/install/divide-and-conquer-smc/lib/ does not exist

### ISSUE THREAD

**Issue by kwajiehao** [alexandrebouchard/divide-and-conquer-smc#5]
Hi, I am trying to compile the provided gradle script but you reference "build/install/divide-and-conquer-smc/lib/" which does not exist even after gradle install. Can you please offer some advice on what I possibly did wrong? The only thing I have done so far is to git clone the repository and used gradle install (as opposed to gradle installApp which did not work for me)

**Comment by alexandrebouchard** [comment]
This is due to a gradle incompatibility. To remove this kind of problems once and for all, I have pushed a new commit with gradle now build in. So do:

```
git pull
./gradlew clean
./gradlew installDist
```

notice that you need now installDist instead of {install, installApp}.

**Comment by kwajiehao** [comment]
I have a separate error now: when I run prepare-data.sh, the error I get is 

> cp: results/latest/preprocessedNYSData.csv: No such file or directory


Even after modifying the shell script, I get an error:

> Error: Could not find or load main class prototype.io.PreprocessNYSchoolData
> Caused by: java.lang.ClassNotFoundException: prototype.io.PreprocessNYSchoolData

It looks like prototype.io.PreprocessNYSchoolData used in the bash script is not available. Do you know what I could do to fix that?

**Comment by alexandrebouchard** [comment]
What do you see when you type 

ls ../build/install/divide-and-conquer-smc/lib/

**Comment by kwajiehao** [comment]
These are the jar files returned:

AMDJ-1.0.1.jar
BTFJ-1.0.1.jar
COLAMDJ-1.0.1.jar
JKLU-1.0.0.jar
JavaEWAH-0.7.9.jar
RCaller-2.1.1.jar
annotations-1.3.2.jar
arpack_combined_all-0.1.jar
bayonet-2.3.19.jar
binc-1.2.1.jar
briefj-2.4.11.jar
cloning-1.9.0.jar
commons-codec-1.4.jar
commons-io-2.4.jar
commons-lang3-3.4.jar
commons-logging-1.1.1.jar
commons-math3-3.6.1.jar
core-lapack-0.1.jar
csparsej-1.1.1.jar
divide-and-conquer-smc.jar
ecj-4.4.jar
ejml-0.24.jar
freemarker-2.3.22.jar
gson-2.3.1.jar
guava-18.0.jar
hamcrest-core-1.3.jar
hazelcast-3.5-EA.jar
hazelcast-code-generator-3.5-EA.jar
httpclient-4.1.3.jar
httpcore-4.1.4.jar
jblas-1.2.4.jar
jcommander-1.47.jar
jgraph-5.13.0.0.jar
jgrapht-core-0.9.0.jar
jgrapht-demo-0.9.0.jar
jgrapht-ext-0.9.0-uber.jar
jgrapht-ext-0.9.0.jar
jgraphx-2.0.0.1.jar
jna-4.2.2.jar
jplasma-1.2.0.jar
jsap-2.1.jar
jsch-0.1.50.jar
jtransforms-2.4.0.jar
junit-4.12.jar
log4j-1.2.17.jar
minimal-json-0.9.2.jar
mvel2-2.1.8.Final.jar
netlib-java-0.9.3.jar
objenesis-1.2.jar
ojalgo-39.0.jar
opencsv-2.3.jar
optimization-1.0.jar
org.eclipse.jgit-3.7.0.201502260915-r.jar
org.eclipse.xtend.lib-2.9.2.jar
org.eclipse.xtend.lib.macro-2.9.2.jar
org.eclipse.xtext.xbase.lib-2.9.2.jar
parallelcolt-0.10.0.jar
slf4j-api-1.7.2.jar
slf4j-simple-1.6.2.jar
spoon-core-4.0.0.jar
sqlite-jdbc-3.8.7.jar
tutorialj-2.0.4.jar
xlinear-1.0.0.jar

**Comment by alexandrebouchard** [comment]
OK so the file divide-and-conquer-smc.jar is there. Please undo the change you did to the script and run the script from the root of the repo as instructed, using "script/prepare-data.sh"

**Comment by kwajiehao** [comment]
perfect, thank you!
